<?php

namespace AppBundle\Repository;

/**
 * ChantierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChantierRepository extends \Doctrine\ORM\EntityRepository
{
}
