<?php

namespace AppBundle\Repository;

/**
 * MarchandiseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MarchandiseRepository extends \Doctrine\ORM\EntityRepository
{
}
